In [62]:
import numpy as np
game=[
    [5,3,0,0,7,0,0,0,0],
    [6,0,0,1,9,5,0,0,0],
    [0,9,8,0,0,0,0,6,0],
    [8,0,0,0,6,0,0,0,3],
    [4,0,0,8,0,3,0,0,1],
    [7,0,0,0,2,0,0,0,6],
    [0,6,0,0,0,0,2,8,0],
    [0,0,0,4,1,9,0,0,5],
    [0,0,0,0,8,0,0,7,9]
]
game=np.matrix(game)
game

matrix([[5, 3, 0, 0, 7, 0, 0, 0, 0],
        [6, 0, 0, 1, 9, 5, 0, 0, 0],
        [0, 9, 8, 0, 0, 0, 0, 6, 0],
        [8, 0, 0, 0, 6, 0, 0, 0, 3],
        [4, 0, 0, 8, 0, 3, 0, 0, 1],
        [7, 0, 0, 0, 2, 0, 0, 0, 6],
        [0, 6, 0, 0, 0, 0, 2, 8, 0],
        [0, 0, 0, 4, 1, 9, 0, 0, 5],
        [0, 0, 0, 0, 8, 0, 0, 7, 9]])

In [63]:
def isInRow(num,r):
    global game
    for c in range(len(game)):
        if game[r,c]==num:
            return True
    return False

In [64]:
def isInCol(num,c):
    global game
    for r in range(len(game)):
        if game[r,c]==num:
            return True
    return False

In [65]:
def isInBox(num,r,c):
    global game
    ranges=[[0,1,2],[3,4,5],[6,7,8]]
    row=ranges[r//3]
    col=ranges[c//3]
    for i in row:
        for j in col:
            if game[i,j]==num:
                return True
    return False

In [66]:
def possible(num,r,c):
    return not isInRow(num,r) and not isInCol(num,c) and not isInBox(num,r,c)

In [67]:
def play():
    global game
    for r in range(len(game)):
        for c in range(len(game)):
            if not game[r,c]:#try to fill a num in blank place
                for num in range(1,10):
                    if possible(num,r,c):
                        game[r,c]=num
                        play()
                        game[r,c]=0
            #if no number can be assigned to that position then return to previous state
            if not game[r,c]:
                return
    print(game)

In [68]:
if __name__=="__main__":
    play()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
